sudo: required
dist: trusty
language: node_js
matrix:
  include:
    - os: osx
    - os: linux
      services: docker
      language: generic

node_js:
  - '8'

install:
  - yarn

script:
  - mv ./src/dev-config.json.example ./src/dev-config.json
  - yarn test-ci
  - yarn dist

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

deploy:
  provider: releases
  api_key:
    secure: Xa5A183n64WSVS19ttTiKm271q8LBkWhB5FffelW3apxmHrTXCQ47bebU9QPzD7C85KB31y/2kxUr7Wet3ky/eUrXxRnehNrpRZqzNMZa4lWu1NkuiSjuf3XhR4d2chi37OjwkJTe8PaA7wOe4FrODUl2Nsq3W5eRNvA8jK+QCRUs2HXlzShx8rZbPNqxVTrMJ0dk1fGCffANN0OuVILdFBGX0e0dm2uZeT/SYA6IdfA/M9FEGZA2K1RLRtYBJ3SrP0Mz8gWvCP72vS/hVV3Kd2uw3ES0ehdOJe1BilJ415hwySxavIJmbSmzG9iHQTipyCjBfLcM3X2m/1R2fagjoAEvgHlRy11DzFnu2ITQl4KeRvFSgV2yfQUvk+axF63INZBinPzHOzVmm3jX88aHojpnkycBbref3XxyaiOrhexrpB0i0XIli/4G0w64lrNGlUvIXO9wafx5MkueQ9lC39E9lYvet3Mct8k17uh/N1+DbetF44odCHnOTp2pegqUSc/KcnukAbQIF1f/UnZiNnpPCc3NF5QNXFX056rAg8hWiA6BaDAB/WZ5mAXwPApN0VK6FKs5LJ1FsIPY4onV9yDy8/ZHThKJLYucmKsCTTRMoQpWVr0oO58KOuKKHGAd47+8nedo5z8QF4ck8fTxKVOFou8NwXdgRVUV5CtDSY=
  skip_cleanup: true
  on:
    repo: vergecurrency/vWallet
    tags: true
